name: Deploy to Vercel (Develop & PR Preview)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '**'

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DEV }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_DEV }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Vercel

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment info
        run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Build project
        run: vercel build --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Preview)
        id: deploy
        run: |
          echo "🚀 Deploying to Vercel Preview..."
          url=$(vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }} | tail -n 1)
          echo "vercel_url=${url}" >> $GITHUB_ENV
          echo "::set-output name=url::$url"

      - name: Comment on PR with Preview URL
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 PR Preview Deployment:\n${{ env.vercel_url }}`
            })

      - name: Comment on develop commit with Preview URL
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: `🚀 Staging Deployment from develop branch:\n${{ env.vercel_url }}`
            })
