name: Deploy to Vercel (Pull Request Preview)

on:
  pull_request:
    branches:
      - '**'

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DEV }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deploy-pr-preview:
    runs-on: ubuntu-latest
    name: Deploy PR Preview to Vercel

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment (preview)
        run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Build project
        run: vercel build --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy PR preview
        id: vercel_preview
        run: |
          echo "🚀 Deploying PR preview..."
          url=$(vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }} | tail -n 1)
          echo "vercel_url=${url}" >> $GITHUB_ENV
          echo "::set-output name=url::$url"

      - name: Comment on PR with Preview URL
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployed for this PR:\n${{ env.vercel_url }}`
            })
